# Build and push BetavilleServer to Docker Hub

on:
  push:
    branches: ['master']

name: Build Betaville Server

jobs:
  deploy:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Checkout Server
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: BetavilleServer

    - name: Checkout App
      uses: actions/checkout@v2
      with:
        repository: Betaville/BetavilleApp
        token: ${{ secrets.GITHUB_TOKEN }}
        path: BetavilleApp
        
    - name: Build Java Source
      id: build-java
      run: cd $GITHUB_WORKSPACE/BetavilleServer/util && ./compile.sh

    - name: Build Docker Image
      id: build-image
      run: |
        # Build a docker container and push it to Docker Hub
        cd cd $GITHUB_WORKSPACE/BetavilleServer
        docker build . -t ${{secrets.DOCKER_HUB_USER}}/betaville-server
        docker push ${{secrets.DOCKER_HUB_USER}}/betaville-server
        